name: text-to-SQL

channels:
  - defaults
  - conda-forge
dependencies:
  - notebook=6.5.4
  - pyyaml=6.0
  - pip=23.0.1
  - pip:
    - langchain
    - langchain_experimental
    - openai
    - python-dotenv
    - chainlit